"""Sampling-time molecular distribution metrics for DiGress.

This module provides torchmetrics-based metrics that evaluate the quality of
molecules generated by the discrete diffusion model at sampling (validation/test)
time.  The main entry point is ``SamplingMolecularMetrics``, which computes
distribution-level statistics (graph size, atom types, bond types, valency) and
RDKit-based validity/uniqueness/novelty scores.

Four distribution metric classes track how closely the generated distributions
match the training dataset:
- ``GeneratedNDistribution`` — distribution over graph sizes
- ``GeneratedNodesDistribution`` — distribution over atom types
- ``GeneratedEdgesDistribution`` — distribution over bond types
- ``ValencyDistribution`` — distribution over per-atom valencies

Each class inherits from ``_NormalizedDistributionMetric``, which provides the
shared ``full_state_update = False`` setting and a ``_normalized()`` helper that
converts raw counts into a probability distribution.
"""

import torch
import torch.nn as nn
from loguru import logger
from torch import Tensor
from torchmetrics import MeanAbsoluteError, Metric
from torch.utils.tensorboard import SummaryWriter

from src.analysis.rdkit_functions import compute_molecular_metrics


_BOND_DISPLAY_NAMES = ("No bond", "Single", "Double", "Triple", "Aromatic")


class _NormalizedDistributionMetric(Metric):
    """Base class for distribution metrics that normalize count tensors to probabilities.

    All subclasses share the ``full_state_update = False`` flag (counts do not
    depend on previous state, only on the current batch) and the ``_normalized``
    helper, which divides a count tensor by its sum to produce a probability
    distribution.
    """

    full_state_update = False

    @staticmethod
    def _normalized(counts: Tensor) -> Tensor:
        """Return counts as a probability distribution (divides by sum).

        Args:
            counts: Non-negative count tensor of any shape.

        Returns:
            Tensor of the same shape with values summing to 1.
        """
        return counts / counts.sum()


class GeneratedNDistribution(_NormalizedDistributionMetric):
    """Tracks the distribution over graph sizes (number of atoms) in generated molecules.

    Args:
        max_n: Maximum number of atoms in any graph. The state tensor has
            shape ``(max_n + 1,)`` so index ``i`` counts graphs with ``i`` atoms.
    """

    def __init__(self, max_n: int) -> None:
        super().__init__()
        self.add_state(
            "n_dist",
            default=torch.zeros(max_n + 1, dtype=torch.float),
            dist_reduce_fx="sum",
        )

    def update(self, molecules: list[tuple[Tensor, Tensor]]) -> None:
        """Increment the count for each molecule's size.

        Args:
            molecules: List of ``(atom_types, edge_types)`` tensors.
        """
        for atom_types, _ in molecules:
            self.n_dist[atom_types.shape[0]] += 1

    def compute(self) -> Tensor:
        """Return the normalized size distribution."""
        return self._normalized(self.n_dist)


class GeneratedNodesDistribution(_NormalizedDistributionMetric):
    """Tracks the distribution over atom types across all generated molecules.

    Args:
        num_atom_types: Number of distinct atom types (dimension of the
            one-hot encoding), determines the length of the count tensor.
    """

    def __init__(self, num_atom_types: int) -> None:
        super().__init__()
        self.add_state(
            "node_dist",
            default=torch.zeros(num_atom_types, dtype=torch.float),
            dist_reduce_fx="sum",
        )

    def update(self, molecules: list[tuple[Tensor, Tensor]]) -> None:
        """Accumulate atom-type counts using bincount.

        Args:
            molecules: List of ``(atom_types, edge_types)`` tensors.
                ``atom_types`` must contain no padding (no ``-1`` values).
        """
        for atom_types, _ in molecules:
            assert (atom_types != -1).all(), (
                "Mask error, the molecules should already be masked at the right shape"
            )
            self.node_dist += torch.bincount(
                atom_types.long(), minlength=len(self.node_dist)
            ).float()

    def compute(self) -> Tensor:
        """Return the normalized atom-type distribution."""
        return self._normalized(self.node_dist)


class GeneratedEdgesDistribution(_NormalizedDistributionMetric):
    """Tracks the distribution over bond types in generated molecular graphs.

    Only upper-triangular edges (excluding the diagonal) are counted to avoid
    double-counting undirected bonds.

    Args:
        num_edge_types: Number of distinct bond types, determines the length
            of the count tensor.
    """

    def __init__(self, num_edge_types: int) -> None:
        super().__init__()
        self.add_state(
            "edge_dist",
            default=torch.zeros(num_edge_types, dtype=torch.float),
            dist_reduce_fx="sum",
        )

    def update(self, molecules: list[tuple[Tensor, Tensor]]) -> None:
        """Accumulate bond-type counts from the upper triangle of each adjacency matrix.

        Args:
            molecules: List of ``(atom_types, edge_types)`` tensors.
        """
        for _, edge_types in molecules:
            mask = torch.triu(torch.ones_like(edge_types), diagonal=1).bool()
            edge_types = edge_types[mask]
            unique_edge_types, counts = torch.unique(
                edge_types, return_counts=True
            )
            self.edge_dist.scatter_add_(
                0, unique_edge_types.long(), counts.float()
            )

    def compute(self) -> Tensor:
        """Return the normalized bond-type distribution."""
        return self._normalized(self.edge_dist)


class ValencyDistribution(_NormalizedDistributionMetric):
    """Tracks the distribution over per-atom valencies in generated molecules.

    Valency is computed as the sum of bond orders for each atom, where aromatic
    bonds (type 4) are counted as 1.5.  The count tensor covers integer valencies
    from 0 to ``3 * max_n - 3`` (the maximum possible valency for a complete graph).

    Args:
        max_n: Maximum number of atoms in any graph.
    """

    def __init__(self, max_n: int) -> None:
        super().__init__()
        self.add_state(
            "edgepernode_dist",
            default=torch.zeros(3 * max_n - 2, dtype=torch.float),
            dist_reduce_fx="sum",
        )

    def update(self, molecules: list[tuple[Tensor, Tensor]]) -> None:
        """Accumulate valency counts across all atoms in the batch.

        Aromatic bonds (encoded as type 4) are replaced with 1.5 before summing
        to give a chemically meaningful valency estimate.

        Args:
            molecules: List of ``(atom_types, edge_types)`` tensors.
        """
        for _, edge_types in molecules:
            edge_types[edge_types == 4] = 1.5
            valencies = torch.sum(edge_types, dim=0)
            unique, counts = torch.unique(valencies, return_counts=True)
            self.edgepernode_dist.scatter_add_(0, unique.long(), counts.float())

    def compute(self) -> Tensor:
        """Return the normalized valency distribution."""
        return self._normalized(self.edgepernode_dist)


class HistogramsMAE(MeanAbsoluteError):
    def __init__(self, target_histogram, **kwargs):
        """Compute the distance between histograms."""
        super().__init__(**kwargs)
        assert (target_histogram.sum() - 1).abs() < 1e-3
        self.target_histogram = target_histogram

    def update(self, pred: torch.Tensor) -> None:
        self.target_histogram = self.target_histogram.type_as(pred)
        super().update(pred / pred.sum(), self.target_histogram)


class SamplingMolecularMetrics(nn.Module):
    """Computes distribution-level and RDKit-based quality metrics for generated molecules.

    At each validation/test step, this module:
    1. Calls RDKit to assess stability, validity, uniqueness, and novelty.
    2. Updates four distribution metrics (graph size, atom types, bond types,
       valency) and computes their MAE against the training dataset.
    3. Assembles a flat ``dict[str, float]`` for TensorBoard logging.

    Args:
        dataset_infos: Object exposing ``max_n_nodes``, ``output_dims``,
            ``n_nodes``, ``node_types``, ``edge_types``,
            ``valency_distribution``, and ``atom_decoder``.
        train_smiles: SMILES strings from the training set, used by RDKit to
            compute novelty.
    """

    def __init__(self, dataset_infos, train_smiles: list[str]) -> None:
        super().__init__()
        self.generated_n_dist = GeneratedNDistribution(dataset_infos.max_n_nodes)
        self.generated_node_dist = GeneratedNodesDistribution(dataset_infos.output_dims["X"])
        self.generated_edge_dist = GeneratedEdgesDistribution(dataset_infos.output_dims["E"])
        self.generated_valency_dist = ValencyDistribution(dataset_infos.max_n_nodes)

        n_target_dist = self._register_target_dist(
            "n_target_dist", dataset_infos.n_nodes, self.generated_n_dist.n_dist
        )
        node_target_dist = self._register_target_dist(
            "node_target_dist", dataset_infos.node_types, self.generated_node_dist.node_dist
        )
        edge_target_dist = self._register_target_dist(
            "edge_target_dist", dataset_infos.edge_types, self.generated_edge_dist.edge_dist
        )
        valency_target_dist = self._register_target_dist(
            "valency_target_dist",
            dataset_infos.valency_distribution,
            self.generated_valency_dist.edgepernode_dist,
        )

        self.n_dist_mae = HistogramsMAE(n_target_dist)
        self.node_dist_mae = HistogramsMAE(node_target_dist)
        self.edge_dist_mae = HistogramsMAE(edge_target_dist)
        self.valency_dist_mae = HistogramsMAE(valency_target_dist)

        self.train_smiles = train_smiles
        self.dataset_info = dataset_infos

    def _register_target_dist(self, name: str, raw: torch.Tensor, ref: torch.Tensor) -> torch.Tensor:
        """Normalizes ``raw`` to a probability distribution, registers it as a buffer, and returns it."""
        dist = raw.type_as(ref)
        dist = dist / dist.sum()
        self.register_buffer(name, dist)
        return dist

    def _update_dist(
        self, dist_metric: Metric, mae_metric: HistogramsMAE, molecules: list
    ) -> torch.Tensor:
        """Updates a distribution metric and its MAE tracker, returning the normalized distribution."""
        dist_metric(molecules)
        result = dist_metric.compute()
        mae_metric(result)
        return result

    def _save_smiles(self, smiles: list[str], path: str) -> None:
        """Write one SMILES string per line to path.

        Args:
            smiles: List of SMILES strings to write.
            path: Output file path.
        """
        with open(path, "w") as fp:
            fp.writelines(f"{s}\n" for s in smiles)
        logger.info("All SMILES saved to %s.", path)

    def forward(
        self,
        molecules: list,
        name,
        current_epoch,
        val_counter,
        local_rank,
        test=False,
        writer: SummaryWriter | None = None,
        global_step: int = 0,
    ) -> dict[str, float]:
        stability, rdkit_metrics, all_smiles = compute_molecular_metrics(
            molecules, self.train_smiles, self.dataset_info
        )

        if test and local_rank == 0:
            self._save_smiles(all_smiles, "final_smiles.txt")

        logger.debug("Computing custom distribution metrics.")
        generated_n_dist = self._update_dist(self.generated_n_dist, self.n_dist_mae, molecules)
        generated_node_dist = self._update_dist(self.generated_node_dist, self.node_dist_mae, molecules)
        generated_edge_dist = self._update_dist(self.generated_edge_dist, self.edge_dist_mae, molecules)
        generated_valency_dist = self._update_dist(self.generated_valency_dist, self.valency_dist_mae, molecules)

        to_log = self._build_to_log(
            generated_node_dist, generated_edge_dist, generated_valency_dist, stability, rdkit_metrics
        )

        if writer is not None:
            for key, val in to_log.items():
                writer.add_scalar(key, val, global_step)
            for tag, dist in [
                ("generated/n_dist", generated_n_dist),
                ("generated/node_dist", generated_node_dist),
                ("generated/edge_dist", generated_edge_dist),
                ("generated/valency_dist", generated_valency_dist),
            ]:
                writer.add_histogram(tag, dist, global_step)

        if local_rank == 0:
            logger.info("Custom metrics computed.")
            with open(f"graphs/{name}/valid_unique_molecules_e{current_epoch}_b{val_counter}.txt", "w") as f:
                f.writelines(rdkit_metrics[1])
            logger.info("Stability: %s | RDKit: %s", stability, rdkit_metrics[0])
        return to_log

    def _build_to_log(
        self,
        generated_node_dist: torch.Tensor,
        generated_edge_dist: torch.Tensor,
        generated_valency_dist: torch.Tensor,
        stability: dict,
        rdkit_metrics: tuple,
    ) -> dict[str, float]:
        """Assembles the metric logging dict from generated distributions and RDKit outputs."""
        to_log = {}
        for i, atom_type in enumerate(self.dataset_info.atom_decoder):
            to_log[f"molecular_metrics/{atom_type}_dist"] = (generated_node_dist[i] - self.node_target_dist[i]).item()
        for j, bond_type in enumerate(_BOND_DISPLAY_NAMES):
            to_log[f"molecular_metrics/bond_{bond_type}_dist"] = (generated_edge_dist[j] - self.edge_target_dist[j]).item()
        for valency in range(6):
            to_log[f"molecular_metrics/valency_{valency}_dist"] = (generated_valency_dist[valency] - self.valency_target_dist[valency]).item()

        to_log["molecular_metrics/n_mae"] = self.n_dist_mae.compute()
        to_log["molecular_metrics/node_mae"] = self.node_dist_mae.compute()
        to_log["molecular_metrics/edge_mae"] = self.edge_dist_mae.compute()
        to_log["molecular_metrics/valency_mae"] = self.valency_dist_mae.compute()

        to_log["molecular_metrics/mol_stable"] = stability["mol_stable"]
        to_log["molecular_metrics/atm_stable"] = stability["atm_stable"]

        validity, relaxed_validity, uniqueness, novelty = rdkit_metrics[0]
        to_log["molecular_metrics/validity"] = validity
        to_log["molecular_metrics/relaxed_validity"] = relaxed_validity
        to_log["molecular_metrics/uniqueness"] = uniqueness
        to_log["molecular_metrics/novelty"] = novelty
        return to_log

    def reset(self):
        for metric in [
            self.n_dist_mae,
            self.node_dist_mae,
            self.edge_dist_mae,
            self.valency_dist_mae,
        ]:
            metric.reset()
